### ISSUE TITLE
Typescript types?

### ISSUE THREAD

**Issue by special-character** [heroku/node-heroku-client#106]
Could we add TS types to this repo for the api options? After a first looksie for `@types/heroku-client` and `@types/node-heroku-client` I didn't see anything.

Happy to add this to another repo if this is not the right spot, thanks!

**Comment by Oaphi** [comment]
Added type definitions for the package to DefinitelyTyped - if anyone would like to provide feedback - feel free to do so on the PR until it is merged (and, of course, after that too).
