### ISSUE TITLE
Extract generic lib to generate clients from schemas

### ISSUE THREAD

**Issue by Papipo** [heroku/node-heroku-client#50]
I think that it would be quite nice to have a javascript library to automatically generate a client from **any JSON schema**, not just Heroku's. Something like [heroics](https://github.com/interagent/heroics) or [Schematic](https://github.com/interagent/schematic)

One could always sprinkle specific stuff on top of it.

**Comment by dickeyxxx** [comment]
this project is generated from schema, do you mean at runtime?

**Comment by jclem** [comment]
@dickeyxxx I think they mean something general for extracting clients from a JSON schema, not specific to the Heroku API client.

**Comment by Papipo** [comment]
Yep @jclem that's what I meant. Sorry if I worded it badly. I added a clarification and some emphasis to the original text.

**Comment by dickeyxxx** [comment]
ah that's definitely out of scope for this library, this is only for using the heroku api

**Comment by dickeyxxx** [comment]
feel free to see if you can extract the code from this to accomplish that though
