### ISSUE TITLE
Buildpack Installation API failure

### ISSUE THREAD

**Issue by pltchuong** [heroku/node-heroku-client#57]
This code return 500, same thing happens with `buildpackInstallations().update` even though I'm pretty sure buildpack still being updated.

```
heroku.apps(<app-id-or-name>).buildpackInstallations().list(function(err, response) {
  console.log("log", err, response);
});
```
I tried with heroku-cli, response still fine 200 with buildpack information. Please check screenshot below 
 
![image](https://cloud.githubusercontent.com/assets/6721317/12340335/21722db4-bacf-11e5-814d-04f256ce0629.png)

![image](https://cloud.githubusercontent.com/assets/6721317/12340372/557555fa-bacf-11e5-958f-bea27b82b07a.png)

**Comment by dickeyxxx** [comment]
can you submit a support ticket? this is an issue inside the API not with the node client
