### ISSUE TITLE
pipelineCouplings always returns 503 and is incorrectly documented

### ISSUE THREAD

**Issue by redbugz** [heroku/node-heroku-client#61]
This code, where pipelineName=`pipelinename` here, but is a real pipeline name in actuality:
```
heroku.pipelines(pipelineName).pipelineCouplings().list().then(function (info) {
    debug('stage info', info);
```
always returns a 503
```
--> GET /pipelines/pipelinename/pipeline-couplings
    accept=application/vnd.heroku+json; version=3
    content-type=application/json
    user-agent=node-heroku-client/2.4.2
    range=id ]..; max=1000
    host=api.heroku.com
    authorization=REDACTED
{ status: 503,
  content_length: '87',
  request_id: '942b02c5-357e-496f-a8ed-057b05bb3a58' }
<-- 503 undefined
    cache-control=private, no-cache
    content-type=application/json
    date=Tue, 22 Mar 2016 11:22:13 GMT
    ratelimit-multiplier=3
    ratelimit-remaining=4497
    request-id=942b02c5-357e-496f-a8ed-057b05bb3a58
    server=nginx/1.8.1
    vary=Accept-Encoding
    x-content-type-options=nosniff
    x-runtime=0.854349235
    content-length=87
    connection=keep-alive
<-- {"id":"unavailable","message":"Could not complete the action. Please try again later."}
deploy:setup failed with error:  { [Error: Expected response to be successful, got 503]
  statusCode: 503,
  body: 
   { id: 'unavailable',
     message: 'Could not complete the action. Please try again later.' } } Error: Expected response to be successful, got 503
```
According to Heroku Support, you cannot use the pipeline name to make the `GET /pipelines/pipelinename/pipeline-couplings` call, but must use the pipeline ID instead. So both the documentation and the code need to be updated to correctly work with pipeline couplings. Similar to how you disambiguate app names, I would hope that you would accept a pipeline name and behind the scenes look up the pipeline id and then make a properly formed request.

**Comment by dickeyxxx** [comment]
It might be the range header. It's caused problems in the past. Can you try making the same request without the range header?

**Comment by redbugz** [comment]
I'm not setting a range header, I'm just using the code listed above to get the couplings for a pipeline

Heroku support said the 503 is because it's using the pipeline name instead of the id, and it's a bug in the schema they will fix

**Comment by redbugz** [comment]
The docs are still incorrect. I cloned and ran bin/update and bin/docs, and no changes are shown, but it still says `pipeline_id_or_name` in https://github.com/heroku/node-heroku-client/blob/master/docs/pipelineCoupling.md. How do we get that updated so it's clear you can only send an id, and your code now needs to look like this:
```
  return heroku.pipelines(pipelineName).info().then(function (pipelineInfo) {
    return heroku.pipelines(pipelineInfo.id).pipelineCouplings().list().then(function (couplings) {
      console.log('couplings', couplings);
    });
  });
```
Also, would it be possible to provide a helper function that does the above work for you, so you just have to work with the pipeline name?

**Comment by dickeyxxx** [comment]
@joshwlewis

**Comment by dickeyxxx** [comment]
my advice is not to use the helper functions at all and just make http calls with this library with `heroku.get()`/`heroku.request()`

**Comment by redbugz** [comment]
So the recommendation would be something like this, or is there a cleaner approach?
```
  heroku.get('/pipelines/' + pipelineName, function (err, info) {
    if (err) {
      console.error('Error reading pipeline', pipelineName, err);
    } else {
      heroku.get(util.format('/pipelines/%s/pipeline-couplings', info.id), function (err, couplings) {
        if (err) {
          console.error('Error reading couplings', pipelineName, err);
        } else {
          console.log('couplings', couplings);
          
        }
      });
    }
  });
```

**Comment by dickeyxxx** [comment]
definitely cleaner if you use promises, but yeah
