### ISSUE TITLE
Module load time is very slow

### ISSUE THREAD

**Issue by dickeyxxx** [heroku/node-heroku-client#64]
Because we heavily depend on this plugin for virtually all Heroku CLI plugins, the module load time is very important. Right now in the new CLI this module takes about 100ms to load because of [this massive file](https://github.com/heroku/node-heroku-client/blob/745b0ade67fb1c78e54bff3047ffb045da65e53f/lib/schema.js) and the inflection that it does. This is over half of the entire time the CLI takes to load.

This wasn't really a problem with the Ruby CLI wrapping the new CLI as it took a (relatively) long time to start, over a second in many cases. The 100ms cost of this was comparatively low. Now that the load time is reduced to less than 200ms, this 100ms is a big cost to the CLI performance.

The proxy objects this generates appear useful, and I used them when first building the CLI code but quickly found them to be less useful than they appear and found myself switching between them and simple `heroku.get/heroku.request` calls. Ultimately I found it was just easier, and even less code to use the manual calls everywhere.

Because I've been discouraging the use of them to users of this client as well as the performance issues we're now experiencing, **I plan to remove proxy objects in a new 3.x release of the package**.

We could improve on the method of calling this module and provide more direction into an opinionated "best" way to use the module. After using this for almost 2 years heavily, I think I have a good idea of what that would look like outlined in #65.

In addition, I think all the dependencies can go away. Currently the production dependencies are:

* **inflection, path-proxy**: Used for the proxy object.
* **q**: node 0.12 is the newest version of node that does not support native promises. Because it is now in maintenance, we can safely drop node <4.x support in the new major version and stick to native promises.
* **tunnel-agent**: I need to investigate a bit further, but I think we can just make the agent configurable and easily allow the calling package to provide tunnel-agent for proxy setups. [The method got uses](https://www.npmjs.com/package/got#proxies) seems ideal here.

This package is however, very stable, and I see no problem with providing updates via a 2.x branch. We will still provide updates to the documentation and updating the API for users that want to continue using it.

**Comment by dickeyxxx** [comment]
cc @ransombriggs

**Comment by ransombriggs** [comment]
@dickeyxxx the right thing to do might be to split our got wrapper out into its own module so that users do not have to think about proxies and just rely on users setting HTTPS_PROXY

**Comment by dickeyxxx** [comment]
Are you suggesting using got for this?
