### ISSUE TITLE
Options for get/post/patch/delete helpers

### ISSUE THREAD

**Issue by dickeyxxx** [heroku/node-heroku-client#65]
Expanding on #64 for items I want to see in a new major version:

Often when using this module, it can be nice to be able to use the helper functions, but they break down when more configuration is needed. For example, if you want to send a `PATCH` request to `/apps/:app_id` to rename an app, you can do the following:

```js
heroku.patch(`/apps/${app}`, {name: 'newname'})
```

This breaks down if you need to do something such as adding headers to the request though, and you need to use `heroku.request` instead:

```js
heroku.request({
  method: 'PATCH',
  path: `/apps/${app}`,
  body: {name: 'newname'},
  headers: {foo: 'bar'}
})
```

This is a pain point. It requires rewriting a lot of code, and the CLI is cluttered with many uses of this. Also, for some reason, `heroku.delete` doesn't take a body. Because of this, I never use the body helper functions and pretty much only use `heroku.get()`.

I think instead of having the second argument to the helpers be a body, we can just change it to request options:

```js
heroku.patch(`/apps/${app}`, {
  body: {name: 'newname'},
  headers: {foo: 'bar'}
})
```

This will make the helpers ultimately flexible, and matches the code with using `heroku.request`. Editing code to add/remove headers, change http method, or anything else requires only small changes to the call, not total rewrites like we have today. This, combined with removing proxy objects will provide an opinionated, yet flexible direction for users.

**Comment by ransombriggs** [comment]
@dickeyxxx is it possible to keep this backwards compatible with the current patch implementation, I am not really seeing how it would be possible in any reliable way, since both the new and old implementations are passed plain objects for the second argument.

**Comment by dickeyxxx** [comment]
no, which is why this would require a major version update
