### ISSUE TITLE
Is caching still included in this package?

### ISSUE THREAD

**Issue by danmartinez101** [heroku/node-heroku-client#70]
Does this module still do etag based caching? I see reference to options.cache in the readme, but from the code I can't tell how those instructions would work.

**Comment by dickeyxxx** [comment]
it will be when 3.0.0 is released, but right now it's not in master. You'll have to use the current release version (2.x)

**Comment by danmartinez101** [comment]
Ah, there it is! Thanks :)

I was thrown off by a combination of two issues:
1. I failed to notice the latest dist tag was a beta
1. I was testing manually against the pipelines resource and the docs are out of date or incorrect: https://devcenter.heroku.com/articles/platform-api-reference#pipeline-list-response-example


Thank you for the very quick reply; you saved me a good deal of time.
