### ISSUE TITLE
Dude token

### ISSUE THREAD

**Issue by ericsuarez** [heroku/node-heroku-client#75]
Hi guys, I have a dude

How I can transform the command **heroku auth:token** using the package? thanxs a lot

**Comment by zeke** [comment]
wat

**Comment by alu0100786330** [comment]
Sorry, I'll try to explain myself better, I want to create a token for a user in my aplication. With the heroku toolbet I make this with the command heroku auth:token. My question is: Can I do the same without the toolbet, just using your node module? Thanks

**Comment by dickeyxxx** [comment]
look at the api docs for creating an oauth token https://devcenter.heroku.com/articles/oauth

you can use this tool to make the requests I think

**Comment by alu0100786330** [comment]
Okey, thanks :)

**Comment by flaviolivolsi** [comment]
I'm still wondering what's a dude token

**Comment by ericsuarez** [comment]
Hahaha, the dude was that I wanted to create a token to authenticate a user with heroku but without using the heroku toolbet.

**Comment by zeke** [comment]
Dude!
