### ISSUE TITLE
Heroku Org Patch Request

### ISSUE THREAD

**Issue by NickLiffen** [heroku/node-heroku-client#76]
Whenever running a PATCH request to Lock an application; it doesn't lock. We get no error message it just outputs the name of the application it has "apparently" locked. 

This is the command we are running to lock the application:

```
console.log("About to Patch Application to lock: ");
herokuClient.patch('organizations/apps/lusa-web-test-prototype', { locked: true }, (err, app) => {
console.log(err);
console.log(app);
}
```

This just returns the app name; no error message.

The output looks like:

`12:22:02 PM web.1 |  Patching Heroku Instance: lusa-web-test-prototype`

Whenever we run a CURL command it locks perfectly. So it's nothing wrong with the API Key?

Is this an issue your side?

**Comment by dickeyxxx** [comment]
this project is for the node client. Do you think that's where the problem is? For an API issue you'll want to submit a support ticket
