### ISSUE TITLE
Consider adding Changelog.md

### ISSUE THREAD

**Issue by brunoscopelliti** [heroku/node-heroku-client#80]
Hi,

my short term question is what has changed (which may break my code) between 2.4.3 and 3.0.2 versions.

I tried [this](https://github.com/heroku/node-heroku-client/compare/f042f39db0b7116f6c495e5eb61bef2d1d360a21...37c643548a86112826b9db4614c9c0276f907999), but it's not particularly clear to someone, like me, who is just a user of the lib.

**update:** *I noticed that your api wrapper now returns promises; is there anything else, which is less immediately observable?*.

On the long term, are you considering adding a Changelog.md file, or could you point me to it, if it does already exists?

Thanks.

**Comment by trollepierre** [comment]
Please add a changelog or release notes
