### ISSUE TITLE
bump form 3.0.4 to 3.0.5 was actually a breaking change.

### ISSUE THREAD

**Issue by joeycozza** [heroku/node-heroku-client#84]
This commit here https://github.com/heroku/node-heroku-client/commit/78bc3d39010bd93e6a467d64c77b509c53da6167 introduced the rest operator (...) which was introduced in node 6. This means that any node code running on node 4 does not work with node-heroku-client@3.0.5.

It would have been nice if semver practices were followed here. Releasing a v4.0.0 would have prevented some legacy code that I have to maintain from breaking.

Along the same notes, in the package.json, it currently said the engines node is ">=4.0.0", but that is not true anymore with the rest operator. That should be updated as well.

**Comment by Akamaozu** [comment]
Would it be wise to revert 3.0.5, save that as 3.0.6 then push the content of 3.0.5 as 4.0.0?

**Comment by jdxcode** [comment]
sorry about the trouble, this is now fixed
