### ISSUE TITLE
Exposing full API response in error messages

### ISSUE THREAD

**Issue by zeke** [heroku/node-heroku-client#86]
Hey @jdxcode and @jclem 👋 

I'm using this client on a project at GitHub. So far it's been a breeze. Thanks for writing this nice module. 📦 

I have noticed that sometimes the error handling is missing information. When I get a `409` or `422` back, the error message doesn't tell me much:

```js
heroku.post('/app-setups', body).catch(err => {
  // console.error(err)
  // Expected response to be successful, got 409
})
```

I've gotten `409` and `422`, both of which can take on different meanings depending on the context and the endpoint being used, so the status code has generally not been enough information to make the underlying problem evident.

Digging into the source, I see that a `body` property is attached to error object:

https://github.com/heroku/node-heroku-client/blob/6c48999a80091152c20d113c5167eaff3edbc40c/lib/request.js#L250-L263

As far as I can tell, this `body` property is both undocumented and non-standard. Looking at the [API for JavaScript's `Error` class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message), they have both a `name` and `message` property that can be used. Maybe we could use the combination of these two properties to have both succinct (`name`) and verbose (`message`) strings in the error object.

Am I on the right track here? If so, would you be open to a pull request that either documents this behavior, or changes the behavior to make error messages more verbose (and useful) by default?

**Comment by jdxcode** [comment]
We don't use this package at Heroku anymore for new code. We use [http-call](https://www.npmjs.com/package/http-call) now. You might want to try using that. It behaves nearly the same.

That said, if you want to use this library, I would be happy to accept a PR for this. It would be a major version bump but that's ok.

**Comment by zeke** [comment]
> We use http-call now.

Good to know. `http-call` appears to be mostly undocumented. What Heroku-specific stuff does it do?

Also, should I open a PR on this repo that mentions it's in "maintenance mode" or something similar?

**Comment by jdxcode** [comment]
the only heroku-specific thing is that it combines multiple requests together when it receives partial range responses. It's more of a generic http library otherwise. Same as this project except this one just defaults the headers.

If dealing with multiple range reponses isn't that important I would just use any old http library.

**Comment by zeke** [comment]
Memories... Thanks for following up @mimen 👍🏼
